[gitdiffnavtool]
ignored-files = false
untracked-files = false
repo-first = false
initial-popup = false
color = red-green
# diff = word-diff
diff = side-by-side
# trim-debug = true
# debug = tmp/gdnt.log
